---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meshnet-env
data:
  # NordVPN client config
  # A token is required for logging in to NordVPN. Please see the docs for token generation.
  # The login token can be set through ENV or supplied into the container using secrets.
  # Token in ENV, comment if you want to use tokenfile.
  NORDVPN_TOKEN: abcdefgh12345678
  # Load token from file (path to mount location), comment to use token ENV.
  NORDVPN_TOKENFILE: /path/to/tokenfile
  # Enable debug mode, anything non-empty will ENABLE. Use this if you need more verbose error logging.
  NORDVPN_MESHNET_DEBUG: ""
  # Healthcheck interval in seconds, default is 300.
  NORDVPN_HEALTHCHECK_INTERVAL: 300
  # Healthcheck URL to verify if connectivity is up. Replace this with something on your Meshnet (if available), defaults to Google.
  NORDVPN_HEALTHCHECK_URL: www.google.com

  # Meshnet permissions
  # In this version of NordVPN, permissions must be configured directly on the client.
  # Configuring peer permissions through the NordVPN account website is still in development.
  # This container will run DENY configuration first, followed by ALLOW. ALLOW will overwrite the DENY!
  # NordVPN currently ALLOWS all peers connected to Meshnet by default.
  # Peers must be entered with their FQDN/Name assigned by Meshnet, comma separated.

  # DENY peer configuration, comma separated.
  # Block peers from using this node as a router
  NORDVPN_DENY_PEER_ROUTING: peer-atlas.nord,peer-fuji.nord
  # Block peers from accessing the local network of this node.
  NORDVPN_DENY_PEER_LOCAL:
  # Block peers from sharing files with this node.
  NORDVPN_DENY_PEER_FILESHARE:
  # Block peers from remote access to this node.
  NORDVPN_DENY_PEER_REMOTE:

  # ALLOW peer configuration
  # Allow peers to use this node as a router
  NORDVPN_ALLOW_PEER_ROUTING:
  # Allow peers to access the local network of this node (ROUTING permissions required!).
  NORDVPN_ALLOW_PEER_LOCAL:
  # Allow peers to  sharing files with this node.
  NORDVPN_ALLOW_PEER_FILESHARE:
  # Allow peers to use remote access on this node.
  NORDVPN_ALLOW_PEER_REMOTE: